server:
  port: 8088
  ssl:
    key-store: classpath:javaboy.p13
    key-alias: tomcat
    key-store-password: 980911
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.blackunique.registry.pojo    # 所有Pojo别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml                       # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enable: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 50
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 10000
    minEvictableIdleTimeMillis: 50000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: 500
        max-idle: 4
        min-idle: 1

logging:
  config: classpath:logback-spring.xml
#  level:
#    com:
#      xietian:
#        graduated:
#          dao: DEBUG
